# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

executors:
  docker:
    docker:
      - image: docker:stable

# Define a job to be invoked later in a workflow.
jobs:
  lint-dockerfile:
    executor: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Run hadolint
          command: docker run --rm --interactive hadolint/hadolint < Dockerfile

  build-app-karsajobs-ui:
    docker:
      - image: cimg/base:2022.09
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push application to Github Packages
          command: |
            # 1. Membuat docker image dari Dockerfile pada direktori sekarang (current directory) dengan nama:tag karsajobs-ui:latest
            docker build -t karsajobs-ui:latest .

            # Mengubah nama image sesuai dengan format GitHub packages
            ## Tagging image
            docker tag karsajobs-ui:latest ghcr.io/muhrizky-a/karsajobs-ui:latest
            
            # 2. Login ke GitHub Packages
            echo $GITHUB_PERSONAL_ACCESS_TOKEN | docker login ghcr.io -u muhrizky-a --password-stdin

            # 3. Push image ke GitHub Packages
            docker push ghcr.io/muhrizky-a/karsajobs-ui:latest

# Orchestrate jobs using workflows
workflows:
  lint-and-build-karsajobs-ui:
    jobs:
      - lint-dockerfile
      - build-app-karsajobs-ui